# Generated by Django 3.0.2 on 2020-01-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=25)),
                ('First_Name', models.CharField(max_length=25)),
                ('Last_Name', models.CharField(max_length=25)),
                ('Category', models.CharField(max_length=25)),
                ('Status', models.CharField(max_length=25)),
                ('Experience', models.CharField(max_length=25)),
                ('Performance', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
