# Generated by Django 3.0.2 on 2020-01-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0002_auto_20200120_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=25)),
                ('First_Name', models.CharField(max_length=25)),
                ('Last_Name', models.CharField(max_length=25)),
                ('Category', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Employee', 'Employee'), ('Staff', 'Staff')], default='Admin', max_length=10)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('Experience', models.CharField(choices=[('Fresher', 'Fresher'), ('Junior', 'Junior'), ('Senior', 'Senior')], default='Fresher', max_length=10)),
                ('Performance', models.CharField(choices=[('Bad', 'Bad'), ('Average', 'Average'), ('Good', 'Good'), ('Excellent', 'Excellent')], default='Average', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='AddAccount',
        ),
    ]
